### ISSUE TITLE
need a example for effect module and post-processing

### ISSUE THREAD

**Issue by HuShiyuFrontEnd** [visgl/luma.gl#1412]
I see there is some document about effect module and some tools like txaa in the shadertools module, but it's difficult to understand how to use it. A simple example is needed.

**Comment by JannikGM** [comment]
I also needed this and my current understanding is that you have to use it like this (with the example for tiltshift):

**Your fragment shader**
```glsl
uniform sampler2D uSampler;
uniform vec2 uSamplerSize;
varying vec2 uv;

void main() {
  gl_FragColor = tiltShift_sampleColor(uSampler, uSamplerSize, uv);
}
```

**main.js**
```js
import {tiltShift} from '@luma.gl/shadertools';

[...]

    const yourTiltShiftModel = new Model(gl, {
      vs: yourVertexShader,
      fs: yourFragmentShader,
      geometry: yourGeometry,
      modules: [tiltShift]
    }).setUniforms({...yourTiltShiftArguments});
```

---

So you add the module to your model and manually use it from the shader.
Most shaders on https://luma.gl/docs/api-reference/shadertools/effects-shader-modules will use this `<effectName>_sampleColor` pattern (I checked the source-code to figure out how to use this).

I believe that's the intended method, because multi-pass rendering was removed in https://github.com/visgl/luma.gl/pull/1278 (which seems to have been added here https://github.com/visgl/luma.gl/issues/715).
There is also https://github.com/visgl/luma.gl/blob/d5bd93ef6bd0a0ff4af7880424286bda269e29a8/dev-docs/RFCs/vNext/automatic-shader-module-injection-rfc.md#motivation which can probably be done via https://luma.gl/docs/api-reference/shadertools/assemble-shaders#shader-hooks-and-module-injections if you want to keep all the actual effect chaining on the JS side.

**Comment by HuShiyuFrontEnd** [comment]
> I also needed this and my current understanding is that you have to use it like this (with the example for tiltshift):
> 
> **Your fragment shader**
> 
> ```glsl
> uniform sampler2D uSampler;
> uniform vec2 uSamplerSize;
> varying vec2 uv;
> 
> void main() {
>   gl_FragColor = tiltShift_sampleColor(uSampler, uSamplerSize, uv);
> }
> ```
> 
> **main.js**
> 
> ```js
> import {tiltShift} from '@luma.gl/shadertools';
> 
> [...]
> 
>     const yourTiltShiftModel = new Model(gl, {
>       vs: yourVertexShader,
>       fs: yourFragmentShader,
>       geometry: yourGeometry,
>       modules: [tiltShift]
>     }).setUniforms({...yourTiltShiftArguments});
> ```
> 
> So you add the module to your model and manually use it from the shader.
> Most shaders on https://luma.gl/docs/api-reference/shadertools/effects-shader-modules will use this `<effectName>_sampleColor` pattern (I checked the source-code to figure out how to use this).
> 
> I believe that's the intended method, because multi-pass rendering was removed in #1278 (which seems to have been added here #715).
> There is also https://github.com/visgl/luma.gl/blob/d5bd93ef6bd0a0ff4af7880424286bda269e29a8/dev-docs/RFCs/vNext/automatic-shader-module-injection-rfc.md#motivation which can probably be done via https://luma.gl/docs/api-reference/shadertools/assemble-shaders#shader-hooks-and-module-injections if you want to keep all the actual effect chaining on the JS side.
> 
> Clearly this needs better documentation. #1460 also seems to be related.

**Comment by HuShiyuFrontEnd** [comment]
oh, i also do something like this. If there is no extra system designed for post-processing, it's a good try.

**Comment by JannikGM** [comment]
I suggest to keep this opened until a maintainer like @ibgreen has commented.
Maybe there is a better system + even if there's no better system, the existing solution should be documented properly.
