### ISSUE TITLE
device is undefined

### ISSUE THREAD

**Issue by zuiidea** [visgl/luma.gl#1634]
- package.json 
```json
{
  "dependencies": {
    "@luma.gl/engine": "8.6.0-alpha.5",
    "@luma.gl/webgl": "8.6.0-alpha.5"
  },
  "devDependencies": {
    "typescript": "^4.6.3",
    "vite": "^2.8.6"
  }
}

```
- source code
```typescript
class AppAnimationLoop extends AnimationLoop {
  onInitialize({ device }) {
    const positionBuffer = device.createBuffer(new Float32Array([-0.5, -0.5, 0.5, -0.5, 0.0, 0.5]))
    ...
    ...
  }
}
```
#### Actual Result

`device` is undefined and It doesn't work.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/16070518/160318961-fd51b9a3-26e5-491f-a237-d1db7cee2f80.png">

#### Expected Result

`device`  has value.

#### Reproduce Steps

reference documentation

https://luma.gl/docs/getting-started/hello-triangle

**Comment by ibgreen** [comment]
@zuiidea Thanks for reporting. 

The reason you are getting this issue is that the `device` object is part of the luma.gl v9 API, but the dependencies in the package.json in luma.gl examples had not been updated. 

- I have published a new `v9.0.0-alpha.4` release and updated example dependencies on master and in docs.
- I have confirmed that `cd examples/get-started/hello-triangle; yarn ; yarn start` works (assuming you have cloned the repo
