### ISSUE TITLE
luma.gl Reference error: window is not defined

### ISSUE THREAD

**Issue by mplatt212** [visgl/luma.gl#1664]
One of the tasks for my current project is trying to find the source of the following console error:

![image](https://user-images.githubusercontent.com/70013024/200417453-b34e003e-be17-4bdb-b65b-c4680c850488.png)

I have looked through all the references to the window object as well as the luma.gl library but can't seem to find where the issue is originating. It doesn't seem to break anything but is more of an annoyance when debugging as it pops up over 20 times in a row whenever the page is refreshed. Here are the versions of Deck.gl and Luma.gl from package.json:

![image](https://user-images.githubusercontent.com/70013024/200417530-1ac8735c-d34b-40c9-b6d8-7da1731dca70.png)

Just want to know if anyone has encountered this before and how you might have fixed it. Thank you.

I have eliminated all calls to the window object within the project to no avail and have looked through polyfill-context.js inside the @luma.gl library with no luck either.

**Comment by ibgreen** [comment]
Not sure if this helps but per the stack trace (`chunk-....js`) you seem to have some hot reloader that is probably doing "clever things" with your run-time environment. You are also pinning `@luma.gl/core` but not immediately clear what version of `@luma.gl/gltools` ends up being pulled in. `yarn why @luma.gl/gltools` or `npm ls @luma.gl/gltools` may shed some light on that - since that is where the error is being reported.

**Comment by mplatt212** [comment]
@ibgreen I'm showing 3 installations of gltools.  This shouldn't be an issue since they're the same version I wouldn't think.  I haven't explicitly added @luma.gl in my package.json so I assume deck.gl is bringing those in.
![image](https://user-images.githubusercontent.com/70013024/200856477-c3e5f8a4-31b6-460f-802c-4645efae8370.png)

**Comment by ibgreen** [comment]
Closing as cause unclear and gltools module has been removed in v9.
