### ISSUE TITLE
If "dimension" is "2d-array", 'WEBGLTexture' will not be initialized correctly.

### ISSUE THREAD

**Issue by Seungup** [visgl/luma.gl#1760]
```ts
import { WEBGLTexture } from '@luma.gl/webgl'

const deivce = ...;

new WEBGLTexture(device, {
  dimension: '2d-array',
  width: width,
  height: height,
  depth: 0,
  data: null,
  format: 'rgba8uint',
  type: GL.UNSIGNED_BYTE,
  mipmaps: false,
  sampler: {
    addressModeU: 'clamp-to-edge',
    addressModeV: 'clamp-to-edge',
    magFilter: 'linear',
    minFilter: 'linear'
  }
});
```

![image](https://github.com/visgl/luma.gl/assets/53374248/bd6de545-5cfe-4aac-8453-351af4692bc5)

I think we should add a case where the value of 'dimension' is '2d-array' to this part. like

```ts
export class WEBGLTexture extends Texture {
   ...

  setImageData(options: SetImageDataOptions) {
    if ( this.props.dimension === '3d' || this.props.dimension === '2d-array' ) {
        return this.setImageData3D(options);
    }
    ...
  }
  
  ...
}
```

https://github.com/visgl/luma.gl/blob/7ee95470a6a2f62753201beb0c36b00e37c70455/modules/webgl/src/adapter/resources/webgl-texture.ts#L442C41-L442C41

**Comment by Seungup** [comment]
I'm using the v9.0.0-alpha.16 version, but it looks like the same problem with alpha.16 will appear on v9.0.0-alpha.21. (No modifications made in versions 21 and 16)

**Comment by ibgreen** [comment]
@Seungup thanks for reporting. I suspect your proposed fix is correct. 

We should add the `2d-array` case to the test suite. The `WEBGLTexture` class is due for a refactor and it will be a good time to do that.

PS - I am impressed that you are trying to use the WIP alpha releases from luma.gl. Are you interested in contributing to the project?

**Comment by Seungup** [comment]
@ibgreen Thank you for your response. I'm glad you agree with my suggested fix and the idea of adding new test cases.

I'm very excited about the potential of contributing to the luma.gl project. To give you a little more context, we're using the alpha versions of luma.gl in our actual company projects. The main reasons for this include the TypeScript support that these versions provide, along with lower overhead and the introduction of the shader module concept. These features were key factors in our decision to choose luma.gl over three.js, and they've allowed us to deeply engage with and contribute to the project.

I'm looking forward to your guidance on the next steps. Thank you!

**Comment by ibgreen** [comment]
@Seungup 

It is great to hear that you find value in luma.gl and its design philosophy. I do want you to have the right expectations if you are using luma.gl v9 for production work. luma.gl v9 is a big breaking release focused on introducing WebGPU and at least until we start publishing beta releases, it will be a work in progress. Happy to try to help you around any rough corners but there are limits to how much support we can provide on an alpha version. That said, if your goal is to work closely to the GPU and you are willing to do some fixes yourself, it may well work out for you.

Regardless, if possible, please join the [deck.gl slack](https://deck.gl/docs/get-started/learning-resources#community) so that we can discuss directly. I have also sent you an invite to the luma.gl repository, so that you can push branches and create PRs directly instead of working through a fork.
