### ISSUE TITLE
Compatibility Inquiry: luma.gl with React 18

### ISSUE THREAD

**Issue by howllian27** [visgl/luma.gl#2095]
#### Background
I am currently working on a project that involves integrating `luma.gl` with a React 18 application. I have encountered several issues regarding dependencies and compatibility with React 18, and I would like to clarify if `luma.gl` is fully compatible with React 18. 

#### Actual Result
While trying to install and integrate `luma.gl` in my React 18 project, I encountered several dependency resolution errors. Specifically, there seem to be conflicts between `luma.gl` and other dependencies that require different versions of React.

#### Expected Result
I would like to confirm if `luma.gl` is designed to be compatible with React 18 and if there are any specific steps or configurations needed to ensure smooth integration.

#### Reproduce Steps
1. Create a new React 18 project.
2. Attempt to install `luma.gl` and other related dependencies (e.g., `deck.gl`).
3. Observe dependency resolution errors during installation.

#### To Do List 
- [ ] Add label and assign to milestone
- [ ] Investigate compatibility issues
- [ ] Update documentation regarding compatibility with React 18
- [ ] Provide guidance on resolving dependency conflicts if applicable

#### Additional Information
Below is the `package.json` file for reference:

```json
{
  "name": "geometry-editor",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@deck.gl/experimental-layers": "^6.4.10",
    "deck.gl": "^9.0.14",
    "gl-matrix": "^3.4.3",
    "luma.gl": "^7.3.2",
    "mapbox-gl": "^3.3.0",
    "maplibre-gl": "^4.3.0",
    "nebula.gl": "^1.0.4",
    "next": "14.2.3",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-map-gl": "^6.1.19",
    "react-map-gl-draw": "^1.0.4"
  },
  "devDependencies": {
    "@types/maplibre-gl": "^1.14.0",
    "@types/node": "^20",
    "@types/react": "^16.14.35",
    "@types/react-dom": "^16.9.14",
    "eslint": "^8",
    "eslint-config-next": "14.2.3",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5",
    "web-vitals": "^4.0.0"
  }
}

**Comment by ibgreen** [comment]
Closing as this is not bug. If you need more help please move this to discussions until we have a confirmed issue.

- luma.gl has no dependencies on React and should work together, there are many applications using them together successfully.
- My guess is that your problem is `@deck.gl/experimental-layers` which is [5 years old](https://www.npmjs.com/package/@deck.gl/experimental-layers). It can not be expected to work with recent deck.gl versions. 
- You should be looking for layer modules that are updated to version 9 if you are going to use deck.g v9.
- Also nebula.gl is no longer supported and has not been updated for deck.gl v9. 
- You can use the supported fork in `@deck.gl-community/editable-layers` instead.
