### ISSUE TITLE
Fails to create context in nwjs

### ISSUE THREAD

**Issue by naturalethic** [visgl/luma.gl#606]
#### Actual Result
```
luma.gl: WebGL contexts can not be created in Node.js since headless gl is not installed. If this is desired, install headless gl using "npm install gl --save-dev" or "yarn add -D gl"
```
#### Expected Result
To create a context.
#### Reproduce Steps
Create a context in an nwjs window

**Comment by naturalethic** [comment]
Note, this works in my console for the window in question:
```
canvas.getContext('webgl2')
WebGL2RenderingContext {canvas: canvas, drawingBufferWidth: 538, drawingBufferHeight: 480}
```

**Comment by ibgreen** [comment]
In a related case, we added some code to [detect electron envs](https://github.com/uber/luma.gl/blob/master/src/utils/is-electron.js), most likely NWJS needs something similar.

We will likely not be able to test this right now (we have a number of releases in the pipe), but since it is likely an easy fix, you are welcome to poke around and provide suggestions / open a PR.
